### ISSUE TITLE
Error while editing plcontainer configuration file.

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/plcontainer#356] opened 2018-05-09 16:39 UTC
I get this error when editing a PL/Container configuration file.

plcontainer:centos73-gp5_90:gpadmin-[INFO]:-Distributing file plcontainer_configuration.xml to all locations...
20180509:09:28:55:017000 plcontainer:centos73-gp5_90:gpadmin-[ERROR]:-[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 433, in execute
    stdout=subprocess.PIPE, close_fds=True)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
20180509:09:28:55:017000 plcontainer:centos73-gp5_90:gpadmin-[CRITICAL]:-plcontainer failed. (Reason=''NoneType' object has no attribute 'wasSuccessful'') exiting...

___
environment 
OS. centos 7 running in VirtualBox vm
gpdb 5.7.0 - single node w/ 2 segments
plcontainer 1.1

I run this command
plcontainer runtime-edit -e vim

add a blank line to the configuration file and exit.

The configuration file is updated and the error appears.

**Comment by HaozhouWang** [comment] 2018-05-11 09:26
@mkiyama Could you please send us the configuration of the VM (how many CPU cores, the size of memory and the size of disk). It looks like the worker is failed to create due to resource limitation.

Thanks a lot!

**Comment by mkiyama** [comment] 2018-05-11 16:53
This is how the vm is configured.

3GB RAM
20 GB disk
1 CPU

FYI - Information about the running system. Hope this helps
```
df .
Filesystem          1K-blocks    Used Available Use% Mounted on
/dev/mapper/cl-root  17811456 6953472  10857984  40% /
```

ran top with gpdb started and running plcontainer runtime-edit -e vim
```
top - 09:47:36 up 3 min,  2 users,  load average: 0.06, 0.11, 0.05
Tasks: 136 total,   3 running, 133 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2915996 total,  1725344 free,   215104 used,   975548 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  1880780 avail Mem
```

**Comment by HaozhouWang** [comment] 2018-05-14 02:33
Thanks @mkiyama 

This may caused due the memory and CPU limitation. The python worker may consume some memory and we do it in parallel. Could you please slightly increase both CPU (to 2 or 3 cores) and Memory (to 4GB+)

If this issue still happened, please let me know. Thanks a lot.

Regards,
Haohzhou

**Comment by mkiyama** [comment] 2018-05-14 16:06
I increased ram to 5120 and cpu to 3
The error still occurs.

**Comment by paul-guo-** [comment] 2018-05-15 02:37
plcontainer utility will not consume that much memory. Have you checked /var/log/messages to see whether there is any special output? What's your 'ulimit -a' output? (increase if needed since I remember that it seems that could affect but I do not remember the details now - note if u modify please add them in your shell profile not just the current shell session). Have you set the kernel parameters as suggested in gpdb doc?

**Comment by mkiyama** [comment] 2018-05-15 15:55
Here is the output of ulimit.
I have also attached my messages file for the session

```
ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 11308
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 131072
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

[messages.zip](https://github.com/greenplum-db/plcontainer/files/2005717/messages.zip)

**Comment by zhangh43** [comment] 2018-05-16 02:23
@mkiyama  Could you run "os.fork()" separately and check whether there is the same error.

**Comment by mkiyama** [comment] 2018-05-17 23:25
[gpadmin@centos73-gp5_90 ~]$ python
Python 2.7.12 (default, Aug 24 2017, 06:49:27)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.fork()
2762
>>> 0
>>>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>> exit()

**Comment by paul-guo-** [comment] 2018-05-18 05:01
This is weird. I suspect the kernel parameter vm.overcommit_memory affects. I assume this value is set following the greenplum doc., so maybe some python modules or other services allocate large virtual memory but may not use finally. Maybe you could try setting vm.overcommit_memory to default value and see whether this issue is still reproducible (sudo users write /proc/sys/vm/overcommit_memory and there's not need to reboot). You could also monitor the vm size when running the command via the top command (Check the VIRT column) to see which process(es) allocate(s) that many virtual memory (and check RES to see its real consumption if you want).

If this is the case, you might want to try adding a swap partition, which will not be used generally if there is no lack of real memory and is just used here to cheat (no harm)

**Comment by mkiyama** [comment] 2018-05-21 22:16
@paul-guo- 
I set vm.overcommit_memory = 1
and do not get the error.

You mentioned this command
sudo users write /proc/sys/vm/overcommit_memory

Is this the correct command to use to set the overcommit_memory?

thanks.

**Comment by paul-guo-** [comment] 2018-05-22 02:16
Sorry, "sudo users write /proc/sys/vm/overcommit_memory" is not a correct command but looks like you've set the parameter correctly.

If you system is lack of memory, I'd suggest you do not  follow gpdb document for that parameter since that is for production environment which is usually equipped with a lot of RAM.

If you really want that setting, you might try a larger or more swap partition(s) or files(s). I do not remember whether additional kernel parameters are needed for this but I suspect no.

**Comment by zhangh43** [comment] 2018-06-23 00:38
Root cause is swap not configured. Close this issue as resolved.

**Closed by zhangh43** 2018-06-23 00:38 UTC
Labels: accepted
